### ISSUE TITLE
Prevent error when deleting input

### ISSUE THREAD

**Issue by guidocioni** [guidocioni/point_wx#143]
I don't know what is causing this (and it is not a big deal) but it could be good to fix it.
I think it happens when we delete too fast the input 

```python
2024-07-02 12:17:28 ERROR app - log_exception: Exception on /pointwx/_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/dash.py", line 1373, in dispatch
    ctx.run(
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/_callback.py", line 465, in add_context
    output_value = _invoke_callback(func, *func_args, **func_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/_callback.py", line 40, in _invoke_callback
    return func(*args, **kwargs)  # %% callback invoked %%
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/point_wx/src/components/location_selector_callbacks.py", line 130, in save_selected_into_cache
    locations_list = locations_list[locations_list["id"] == selected[0]["value"]]
                                                            ~~~~~~~~^^^
IndexError: list index out of range
```

Probably when `selected` or `locations_list` are not defined??

We need to reproduce the error and add an `if` statement with a `raise PreventUpdate`

**Comment by guidocioni** [comment]
Should be solved in 4a40643d6c3eb6ee6d443996019261b3aabe873f
