### ISSUE TITLE
Errors in `create_options` when `admin_3` is not present

### ISSUE THREAD

**Issue by guidocioni** [guidocioni/point_wx#144]
For example for `Beijing`

```python
Traceback (most recent call last):
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'admin3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/dash.py", line 1373, in dispatch
    ctx.run(
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/_callback.py", line 465, in add_context
    output_value = _invoke_callback(func, *func_args, **func_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/_callback.py", line 40, in _invoke_callback
    return func(*args, **kwargs)  # %% callback invoked %%
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/point_wx/src/components/location_selector_callbacks.py", line 101, in suggest_locs_dropdown
    options = create_options(locations)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/point_wx/src/components/location_selector_callbacks.py", line 39, in create_options
    locations["label"] = locations.apply(formatter, axis=1)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/point_wx/src/components/location_selector_callbacks.py", line 34, in formatter
    f"{', '+ x['admin3'] if x['duplicated_name_and_region'] and pd.isna(x['admin2']) else ''}"
             ~^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'admin3'
```

or 

```python
Traceback (most recent call last):
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/dash.py", line 1373, in dispatch
    ctx.run(
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/_callback.py", line 465, in add_context
    output_value = _invoke_callback(func, *func_args, **func_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/dash/_callback.py", line 40, in _invoke_callback
    return func(*args, **kwargs)  # %% callback invoked %%
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/point_wx/src/components/location_selector_callbacks.py", line 101, in suggest_locs_dropdown
    options = create_options(locations)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/point_wx/src/components/location_selector_callbacks.py", line 39, in create_options
    locations["label"] = locations.apply(formatter, axis=1)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/miniconda3/envs/dash/lib/python3.12/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guidocioni/point_wx/src/components/location_selector_callbacks.py", line 34, in formatter
    f"{', '+ x['admin3'] if x['duplicated_name_and_region'] and pd.isna(x['admin2']) else ''}"
       ~~~~^~~~~~~~~~~~~
TypeError: can only concatenate str (not "float") to str
```

Only use `admin3` if it is there

**Comment by guidocioni** [comment]
Should be fixed by 29120ad76fec5902fd88400909dc0c9b7ed54257.
To be monitored
