### ISSUE TITLE
Page not loading properly

### ISSUE THREAD

**Issue by guidocioni** [guidocioni/point_wx#89]
When loading the page sometimes an error is thrown 

```
dash_renderer.v2_9_2m1680247231.min.js:2 TypeError: Cannot read properties of undefined (reading 'apply')
    at dash_renderer.v2_9_2m1680247231.min.js:2:126547
    at s (dash_renderer.v2_9_2m1680247231.min.js:2:116518)
    at Generator._invoke (dash_renderer.v2_9_2m1680247231.min.js:2:116271)
    at Generator.next (dash_renderer.v2_9_2m1680247231.min.js:2:116881)
    at Sa (dash_renderer.v2_9_2m1680247231.min.js:2:122459)
    at a (dash_renderer.v2_9_2m1680247231.min.js:2:122663)
    at dash_renderer.v2_9_2m1680247231.min.js:2:122724
    at new Promise (<anonymous>)
    at dash_renderer.v2_9_2m1680247231.min.js:2:122603
    at nu (dash_renderer.v2_9_2m1680247231.min.js:2:125665)
```

This makes all the clientside callbacks fail (like the one automatically collapsing the navbar or the one scrolling to the plot).

Refreshing the page sometimes get rid of the error, but not always...it seems to be just random so hard to reproduce.

As it is never happening locally maybe we should try updating Dash on the server, which still has an old version?

**Comment by guidocioni** [comment]
Seems to be fixed by updating dash
